export const cardHeader: string;
export const cardBody: string;
export const cardFooter: string;
export const cardImage: string;
export const cardActions: string;
export const cardTitle: string;
export const cardDescription: string;
export const cardMeta: string;
export const cardBadgeGroup: string;
