declare const styles: {
  readonly imageCard: string;
  readonly imageCardCompact: string;
  readonly imageElement: string;
  readonly imageHidden: string;
  readonly imagePositionCenter: string;
  readonly imagePositionTop: string;
  readonly imagePositionBottom: string;
  readonly imagePositionLeft: string;
  readonly imagePositionRight: string;
  readonly loadingContainer: string;
  readonly errorContainer: string;
  readonly emptyContainer: string;
  readonly visuallyHidden: string;
  readonly gradientOverlay: string;
  readonly badge: string;
  readonly badgeTopLeft: string;
  readonly badgeTopRight: string;
  readonly content: string;
  readonly contentNoAction: string;
  readonly title: string;
  readonly titleLines1: string;
  readonly titleLines2: string;
  readonly titleLines3: string;
  readonly subtitle: string;
  readonly subtitleLines1: string;
  readonly subtitleLines2: string;
  readonly subtitleLines3: string;
  readonly actionButton: string;
};

export default styles;
