import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';

// PostCSS config (postcss.config.mjs) is automatically picked up by Vite
// It includes: @tailwindcss/postcss, our breakpoint mixins, postcss-nested, autoprefixer

export default defineConfig({
  plugins: [react()],
  build: {
    emptyOutDir: false, // Preserve .d.ts files generated by tsc
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'AINativeKitUI',
      formats: ['es', 'cjs'],
      fileName: (format) => {
        const ext = format === 'es' ? 'js' : 'cjs';
        return `index.${ext}`;
      },
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'react/jsx-runtime'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
        },
      },
    },
    cssCodeSplit: false,
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
    },
  },
});
